# Setup
title:            Ben Bolte's Blog
tagline:          Hi! 👋 I'm Ben.
baseurl:          ""

# Contact
email:            ben@bolte.cc

usernames:
  github:         codekansas
  twitter:        code__kansas

# Sass
sass:
  sass_dir:       assets/css/sass

# Some CDN-hosted scripts
cdn:
  bootstrap-css:  https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
  katex:          https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css
  mathjax:        https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

# Other
markdown:         kramdown
kramdown:
  math_engine_opts:
    preview:      true
    preview_as_code: true
permalink:        :title

katex:
  rendering_options:
    throw_error:  true

# Analytics
analytics:
  google:         UA-77147392-2
  facebook:       516160742657752

