# Setup
title:            codekansas
tagline:          A blog of language, neuroscience, and deep learning
baseurl:          ""

# Contact
email:            ben@bolte.cc

usernames:
  github:         codekansas
  twitter:        code__kansas
  facebook:       codekansas

# Sass
sass:
  sass_dir:       assets/css/sass

# Some CDN-hosted scripts
cdn:
  mathjax:        https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  d3js:           https://cdnjs.cloudflare.com/ajax/libs/d3/4.13.0/d3.min.js
  mathjs:         https://cdnjs.cloudflare.com/ajax/libs/mathjs/3.16.3/math.min.js
  kerasjs:        https://cdnjs.cloudflare.com/ajax/libs/keras-js/0.3.0/keras.js
  kerasjs-legacy: /assets/js/keras.min.js
  bscss:          https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  bsjs:           https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
  jquery:         https://code.jquery.com/jquery-3.2.1.min.js
  jq-cookie:      https://cdn.jsdelivr.net/npm/jquery.cookie@1.4.1/jquery.cookie.min.js
  porter:         https://rawgit.com/codekansas/porter-stemmer-js/master/porter.min.js
  tfjs:           https://cdn.jsdelivr.net/npm/@tensorflow/tfjs

# Other
markdown:         kramdown
permalink:        :title
