# Setup
title:            Ben Bolte's Blog
tagline:          Hi! 👋 I'm Ben.
baseurl:          ""

# Contact
email:            ben@bolte.cc

usernames:
  github:         codekansas
  twitter:        code__kansas

# Sass
sass:
  sass_dir:       assets/css/sass

# Some CDN-hosted scripts
cdn:
  mathjax:        https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Other
markdown:         kramdown
permalink:        :title
